version: '3.8'

services:
  web:
    build: .
    image: apka
    container_name: apka
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    devices:
      - /dev/video0:/dev/video0